# dotenv: .env

dependencies:
  #  - <org/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - smartcontractkit/chainlink-mix@2.3.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
      - '@chainlink-mix=smartcontractkit/chainlink-mix@2.3.0'

networks:
  default: development
  dev-fork: 
    eth_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  mainnet-fork: 
    eth_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  kovan: 
    eth_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  rinkeby:
    eth_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  developement:
    verify: False
  ganachewin11:
    verify: False